#!/usr/bin/env python3
"""Emit adaptive-icon vector layers + a verification SVG from shared geometry.

Writes:
  android/app/src/main/res/drawable/ic_launcher_background.xml  (vector, gradient)
  android/app/src/main/res/drawable/ic_launcher_foreground.xml  (vector, glyph)
  android/tools/ic_launcher_foreground_preview.svg              (render check)

The geometry math is imported from generate_launcher_icons.py so the PNG
fallbacks and the adaptive vector can never drift apart.
"""
import math
import os

from generate_launcher_icons import (
    ARCS,
    BAND_INNER,
    BAND_OUTER,
    C1,
    C2,
    CENTER,
    RES_DIR,
    arrowhead_polygon,
    point,
)

FLOAT = lambda v: f"{v:.3f}".rstrip("0").rstrip(".")


def arc_band_path(start: float, end: float) -> str:
    """Closed band: outer arc (cw), radial cap, inner arc (ccw), radial cap."""
    o_s = point(start, BAND_OUTER)
    o_e = point(end, BAND_OUTER)
    i_e = point(end, BAND_INNER)
    i_s = point(start, BAND_INNER)
    large = 1 if (end - start) % 360 > 180 else 0
    return (
        f"M{FLOAT(o_s[0])},{FLOAT(o_s[1])}"
        f" A{FLOAT(BAND_OUTER)},{FLOAT(BAND_OUTER)} 0 {large} 1 {FLOAT(o_e[0])},{FLOAT(o_e[1])}"
        f" L{FLOAT(i_e[0])},{FLOAT(i_e[1])}"
        f" A{FLOAT(BAND_INNER)},{FLOAT(BAND_INNER)} 0 {large} 0 {FLOAT(i_s[0])},{FLOAT(i_s[1])} Z"
    )


def polygon_path(points) -> str:
    coords = [(x, y) for x, y in points]
    head = f"M{FLOAT(coords[0][0])},{FLOAT(coords[0][1])}"
    tail = "".join(f" L{FLOAT(x)},{FLOAT(y)}" for x, y in coords[1:])
    return head + tail + " Z"


def diamond_path(radius: float) -> str:
    pts = [
        (CENTER, CENTER - radius),
        (CENTER + radius, CENTER),
        (CENTER, CENTER + radius),
        (CENTER - radius, CENTER),
    ]
    return polygon_path(pts)


FOREGROUND_PATHS = [arc_band_path(s, e) for s, e in ARCS] + [
    polygon_path(arrowhead_polygon(ARCS[0][1])),
    polygon_path(arrowhead_polygon(ARCS[1][1])),
    diamond_path(14.0),
    diamond_path(6.5),
]

FOREGROUND_XML = f"""<?xml version="1.0" encoding="utf-8"?>
<!-- FreeLanSync adaptive-icon foreground. GENERATED by android/tools/generate_vector_layers.py
     (same geometry as the mipmap PNG fallbacks): edit the generator, not this file. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">

    <!-- Sync ring band, two arcs -->
    <path android:fillColor="#38BDF8" android:pathData="{FOREGROUND_PATHS[0]}" />
    <path android:fillColor="#38BDF8" android:pathData="{FOREGROUND_PATHS[1]}" />
    <!-- Arrowheads -->
    <path android:fillColor="#38BDF8" android:pathData="{FOREGROUND_PATHS[2]}" />
    <path android:fillColor="#38BDF8" android:pathData="{FOREGROUND_PATHS[3]}" />
    <!-- Brand diamond core (outer white, inner cyan) -->
    <path android:fillColor="#FFFFFF" android:pathData="{FOREGROUND_PATHS[4]}" />
    <path android:fillColor="#38BDF8" android:pathData="{FOREGROUND_PATHS[5]}" />
</vector>
"""

BACKGROUND_XML = f"""<?xml version="1.0" encoding="utf-8"?>
<!-- FreeLanSync adaptive-icon background: indigo-900 -> slate-900 diagonal gradient. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:aapt="http://schemas.android.com/aapt"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
    <path android:pathData="M0,0 H108 V108 H0 Z">
        <aapt:attr name="android:fillColor">
            <gradient
                android:type="linear"
                android:startX="0"
                android:startY="0"
                android:endX="108"
                android:endY="108"
                android:startColor="#FF{C1[0]:02X}{C1[1]:02X}{C1[2]:02X}"
                android:endColor="#FF{C2[0]:02X}{C2[1]:02X}{C2[2]:02X}" />
        </aapt:attr>
    </path>
</vector>
"""


def foreground_svg() -> str:
    """Same paths as SVG for a pixel-parity visual check against the PNG."""
    def esc(p: str) -> str:
        return p  # path syntax is identical between Android vector and SVG

    grad = (
        f'<linearGradient id="bg" x1="0" y1="0" x2="108" y2="108" gradientUnits="userSpaceOnUse">'
        f'<stop stop-color="#{C1[0]:02X}{C1[1]:02X}{C1[2]:02X}"/>'
        f'<stop offset="1" stop-color="#{C2[0]:02X}{C2[1]:02X}{C2[2]:02X}"/>'
        f"</linearGradient>"
    )
    paths = "\n".join(
        f'<path d="{esc(p)}" fill="{"#38BDF8" if i < 4 else ("#FFFFFF" if i == 4 else "#38BDF8")}"/>'
        for i, p in enumerate(FOREGROUND_PATHS)
    )
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" width="1080" height="1080" viewBox="0 0 108 108">'
        f"<defs>{grad}</defs>"
        f'<rect width="108" height="108" fill="url(#bg)"/>'
        f"{paths}"
        f"</svg>"
    )


def main():
    fg_path = os.path.join(RES_DIR, "drawable", "ic_launcher_foreground.xml")
    bg_path = os.path.join(RES_DIR, "drawable", "ic_launcher_background.xml")
    os.makedirs(os.path.dirname(fg_path), exist_ok=True)
    with open(fg_path, "w", encoding="utf-8") as f:
        f.write(FOREGROUND_XML)
    with open(bg_path, "w", encoding="utf-8") as f:
        f.write(BACKGROUND_XML)
    print(f"wrote {fg_path}")
    print(f"wrote {bg_path}")

    svg_path = os.path.join(os.path.dirname(__file__), "ic_launcher_foreground_preview.svg")
    with open(svg_path, "w", encoding="utf-8") as f:
        f.write(foreground_svg())
    print(f"wrote {svg_path}")


if __name__ == "__main__":
    main()
